/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dale' at '16. 11. 18 오후 9:54' with Gradle 3.1
 *
 * @author Dale, @date 16. 11. 18 오후 9:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
